import getSymbolFromCurrency from "currency-symbol-map";

export const SUPPORTED_CURRENCIES = [
  { code: "PKR", label: "Pakistani Rupee", locale: "en-PK" },
  { code: "INR", label: "Indian Rupee", locale: "en-IN" },
  { code: "USD", label: "US Dollar", locale: "en-US" },
  { code: "AED", label: "UAE Dirham", locale: "en-AE" },
  { code: "SAR", label: "Saudi Riyal", locale: "en-SA" },
  { code: "EUR", label: "Euro", locale: "en-IE" },
  { code: "GBP", label: "British Pound", locale: "en-GB" },
  { code: "AUD", label: "Australian Dollar", locale: "en-AU" },
  { code: "BDT", label: "Bangladeshi Taka", locale: "bn-BD" },
  { code: "BHD", label: "Bahraini Dinar", locale: "ar-BH" },
  { code: "BND", label: "Brunei Dollar", locale: "ms-BN" },
  { code: "BRL", label: "Brazilian Real", locale: "pt-BR" },
  { code: "CAD", label: "Canadian Dollar", locale: "en-CA" },
  { code: "CHF", label: "Swiss Franc", locale: "de-CH" },
  { code: "CLP", label: "Chilean Peso", locale: "es-CL" },
  { code: "CNY", label: "Chinese Yuan", locale: "zh-CN" },
  { code: "COP", label: "Colombian Peso", locale: "es-CO" },
  { code: "CRC", label: "Costa Rican Colon", locale: "es-CR" },
  { code: "CZK", label: "Czech Koruna", locale: "cs-CZ" },
  { code: "DKK", label: "Danish Krone", locale: "da-DK" },
  { code: "DOP", label: "Dominican Peso", locale: "es-DO" },
  { code: "DZD", label: "Algerian Dinar", locale: "ar-DZ" },
  { code: "EGP", label: "Egyptian Pound", locale: "ar-EG" },
  { code: "ETB", label: "Ethiopian Birr", locale: "am-ET" },
  { code: "FJD", label: "Fijian Dollar", locale: "en-FJ" },
  { code: "GEL", label: "Georgian Lari", locale: "ka-GE" },
  { code: "GHS", label: "Ghanaian Cedi", locale: "en-GH" },
  { code: "GTQ", label: "Guatemalan Quetzal", locale: "es-GT" },
  { code: "HKD", label: "Hong Kong Dollar", locale: "zh-HK" },
  { code: "HNL", label: "Honduran Lempira", locale: "es-HN" },
  { code: "HRK", label: "Croatian Kuna", locale: "hr-HR" },
  { code: "HUF", label: "Hungarian Forint", locale: "hu-HU" },
  { code: "IDR", label: "Indonesian Rupiah", locale: "id-ID" },
  { code: "ILS", label: "Israeli New Shekel", locale: "he-IL" },
  { code: "IQD", label: "Iraqi Dinar", locale: "ar-IQ" },
  { code: "IRR", label: "Iranian Rial", locale: "fa-IR" },
  { code: "ISK", label: "Icelandic Krona", locale: "is-IS" },
  { code: "JMD", label: "Jamaican Dollar", locale: "en-JM" },
  { code: "JOD", label: "Jordanian Dinar", locale: "ar-JO" },
  { code: "JPY", label: "Japanese Yen", locale: "ja-JP" },
  { code: "KES", label: "Kenyan Shilling", locale: "en-KE" },
  { code: "KGS", label: "Kyrgyzstani Som", locale: "ky-KG" },
  { code: "KHR", label: "Cambodian Riel", locale: "km-KH" },
  { code: "KWD", label: "Kuwaiti Dinar", locale: "ar-KW" },
  { code: "KZT", label: "Kazakhstani Tenge", locale: "kk-KZ" },
  { code: "LAK", label: "Lao Kip", locale: "lo-LA" },
  { code: "LBP", label: "Lebanese Pound", locale: "ar-LB" },
  { code: "LKR", label: "Sri Lankan Rupee", locale: "si-LK" },
  { code: "MAD", label: "Moroccan Dirham", locale: "ar-MA" },
  { code: "MDL", label: "Moldovan Leu", locale: "ro-MD" },
  { code: "MGA", label: "Malagasy Ariary", locale: "mg-MG" },
  { code: "MKD", label: "Macedonian Denar", locale: "mk-MK" },
  { code: "MMK", label: "Myanmar Kyat", locale: "my-MM" },
  { code: "MNT", label: "Mongolian Tugrik", locale: "mn-MN" },
  { code: "MOP", label: "Macanese Pataca", locale: "zh-MO" },
  { code: "MUR", label: "Mauritian Rupee", locale: "en-MU" },
  { code: "MVR", label: "Maldivian Rufiyaa", locale: "dv-MV" },
  { code: "MXN", label: "Mexican Peso", locale: "es-MX" },
  { code: "MYR", label: "Malaysian Ringgit", locale: "ms-MY" },
  { code: "NAD", label: "Namibian Dollar", locale: "en-NA" },
  { code: "NGN", label: "Nigerian Naira", locale: "en-NG" },
  { code: "NIO", label: "Nicaraguan Cordoba", locale: "es-NI" },
  { code: "NOK", label: "Norwegian Krone", locale: "nb-NO" },
  { code: "NPR", label: "Nepalese Rupee", locale: "ne-NP" },
  { code: "NZD", label: "New Zealand Dollar", locale: "en-NZ" },
  { code: "OMR", label: "Omani Rial", locale: "ar-OM" },
  { code: "PAB", label: "Panamanian Balboa", locale: "es-PA" },
  { code: "PEN", label: "Peruvian Sol", locale: "es-PE" },
  { code: "PHP", label: "Philippine Peso", locale: "en-PH" },
  { code: "PLN", label: "Polish Zloty", locale: "pl-PL" },
  { code: "PYG", label: "Paraguayan Guarani", locale: "es-PY" },
  { code: "QAR", label: "Qatari Riyal", locale: "ar-QA" },
  { code: "RON", label: "Romanian Leu", locale: "ro-RO" },
  { code: "RSD", label: "Serbian Dinar", locale: "sr-RS" },
  { code: "RUB", label: "Russian Ruble", locale: "ru-RU" },
  { code: "SEK", label: "Swedish Krona", locale: "sv-SE" },
  { code: "SGD", label: "Singapore Dollar", locale: "en-SG" },
  { code: "THB", label: "Thai Baht", locale: "th-TH" },
  { code: "TND", label: "Tunisian Dinar", locale: "ar-TN" },
  { code: "TRY", label: "Turkish Lira", locale: "tr-TR" },
  { code: "TTD", label: "Trinidad and Tobago Dollar", locale: "en-TT" },
  { code: "TWD", label: "New Taiwan Dollar", locale: "zh-TW" },
  { code: "TZS", label: "Tanzanian Shilling", locale: "sw-TZ" },
  { code: "UAH", label: "Ukrainian Hryvnia", locale: "uk-UA" },
  { code: "UGX", label: "Ugandan Shilling", locale: "en-UG" },
  { code: "UYU", label: "Uruguayan Peso", locale: "es-UY" },
  { code: "UZS", label: "Uzbekistani Som", locale: "uz-UZ" },
  { code: "VND", label: "Vietnamese Dong", locale: "vi-VN" },
  { code: "XAF", label: "Central African CFA Franc", locale: "fr-CM" },
  { code: "XOF", label: "West African CFA Franc", locale: "fr-SN" },
  { code: "YER", label: "Yemeni Rial", locale: "ar-YE" },
  { code: "ZAR", label: "South African Rand", locale: "en-ZA" },
  { code: "ZMW", label: "Zambian Kwacha", locale: "en-ZM" },
  { code: "ALL", label: "Albanian Lek", locale: "sq-AL" },
  { code: "AMD", label: "Armenian Dram", locale: "hy-AM" },
  { code: "AOA", label: "Angolan Kwanza", locale: "pt-AO" },
  { code: "ARS", label: "Argentine Peso", locale: "es-AR" },
  { code: "AZN", label: "Azerbaijani Manat", locale: "az-AZ" },
  {
    code: "BAM",
    label: "Bosnia and Herzegovina Convertible Mark",
    locale: "bs-BA",
  },
  { code: "BBD", label: "Barbadian Dollar", locale: "en-BB" },
  { code: "BIF", label: "Burundian Franc", locale: "fr-BI" },
  { code: "BMD", label: "Bermudian Dollar", locale: "en-BM" },
  { code: "BOB", label: "Bolivian Boliviano", locale: "es-BO" },
  { code: "BSD", label: "Bahamian Dollar", locale: "en-BS" },
  { code: "BWP", label: "Botswana Pula", locale: "en-BW" },
  { code: "BYN", label: "Belarusian Ruble", locale: "be-BY" },
  { code: "CDF", label: "Congolese Franc", locale: "fr-CD" },
  { code: "CUP", label: "Cuban Peso", locale: "es-CU" },
  { code: "CVE", label: "Cape Verdean Escudo", locale: "pt-CV" },
  { code: "DJF", label: "Djiboutian Franc", locale: "fr-DJ" },
  { code: "ERN", label: "Eritrean Nakfa", locale: "ti-ER" },
  { code: "FKP", label: "Falkland Islands Pound", locale: "en-FK" },
  { code: "GIP", label: "Gibraltar Pound", locale: "en-GI" },
  { code: "GMD", label: "Gambian Dalasi", locale: "en-GM" },
  { code: "GNF", label: "Guinean Franc", locale: "fr-GN" },
  { code: "GYD", label: "Guyanese Dollar", locale: "en-GY" },
  { code: "KMF", label: "Comorian Franc", locale: "fr-KM" },
  { code: "KYD", label: "Cayman Islands Dollar", locale: "en-KY" },
  { code: "LRD", label: "Liberian Dollar", locale: "en-LR" },
  { code: "LSL", label: "Lesotho Loti", locale: "en-LS" },
  { code: "LYD", label: "Libyan Dinar", locale: "ar-LY" },
  { code: "MZN", label: "Mozambican Metical", locale: "pt-MZ" },
  { code: "SBD", label: "Solomon Islands Dollar", locale: "en-SB" },
  { code: "SCR", label: "Seychellois Rupee", locale: "en-SC" },
  { code: "SDG", label: "Sudanese Pound", locale: "ar-SD" },
  { code: "SHP", label: "Saint Helena Pound", locale: "en-SH" },
  { code: "SLL", label: "Sierra Leonean Leone", locale: "en-SL" },
  { code: "SOS", label: "Somali Shilling", locale: "so-SO" },
  { code: "SRD", label: "Surinamese Dollar", locale: "nl-SR" },
  { code: "SSP", label: "South Sudanese Pound", locale: "en-SS" },
  { code: "SYP", label: "Syrian Pound", locale: "ar-SY" },
  { code: "TOP", label: "Tongan Paanga", locale: "to-TO" },
  { code: "VES", label: "Venezuelan Bolivar", locale: "es-VE" },
  { code: "WST", label: "Samoan Tala", locale: "sm-WS" },
  { code: "XCD", label: "East Caribbean Dollar", locale: "en-AG" },
  { code: "ZWL", label: "Zimbabwean Dollar", locale: "en-ZW" },
];

export const DEFAULT_CURRENCY = "PKR";
export const DEFAULT_LOCALE = "en-PK";

export function getCurrencyMeta(code) {
  return (
    SUPPORTED_CURRENCIES.find((c) => c.code === code) || SUPPORTED_CURRENCIES[0]
  );
}

export function getCurrencySymbol(code) {
  return getSymbolFromCurrency(code) || code;
}
