import { format } from "date-fns";
import { formatCurrency, formatDate, formatDateTime } from "./format";

function getNestedValue(obj, key) {
  if (!key.includes(".")) return obj?.[key];
  return key.split(".").reduce((acc, part) => acc?.[part], obj);
}

function normalizeCell(value, formatType) {
  if (formatType === "currency") return formatCurrency(value || 0);
  if (formatType === "date") return formatDate(value);
  if (formatType === "datetime") return formatDateTime(value);
  if (Array.isArray(value)) return value.join(" | ");
  if (value == null) return "";
  return String(value);
}

function escapeCsv(value) {
  const text = String(value ?? "");
  if (/[",\n\r]/.test(text)) {
    return `"${text.replace(/"/g, '""')}"`;
  }
  return text;
}

export function exportToCSV(data, columns, filename) {
  const header = columns.map((column) => escapeCsv(column.label)).join(",");
  const rows = data.map((row) =>
    columns
      .map((column) => {
        const raw = getNestedValue(row, column.key);
        const val = normalizeCell(raw, column.format);
        return escapeCsv(val);
      })
      .join(","),
  );

  const csv = [header, ...rows].join("\n");
  const blob = new Blob(["\ufeff" + csv], {
    type: "text/csv;charset=utf-8;",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename}-${format(new Date(), "yyyy-MM-dd")}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToJSON(data, filename) {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename}-${format(new Date(), "yyyy-MM-dd")}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function generatePrintReport(title, stats = [], table = {}) {
  const reportWindow = window.open("", "_blank", "width=1100,height=800");
  if (!reportWindow) return;

  const statHtml = stats
    .map(
      (item) =>
        `<div class="stat"><div class="label">${item.label}</div><div class="value">${item.value}</div></div>`,
    )
    .join("");

  const head = (table.columns || [])
    .map((col) => `<th>${col.label}</th>`)
    .join("");

  const body = (table.rows || [])
    .map(
      (row) =>
        `<tr>${(table.columns || [])
          .map(
            (col) =>
              `<td>${normalizeCell(getNestedValue(row, col.key), col.format)}</td>`,
          )
          .join("")}</tr>`,
    )
    .join("");

  reportWindow.document.write(`
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 28px; color: #122; }
          h1 { margin: 0 0 4px; font-size: 24px; }
          .meta { color: #556; font-size: 12px; margin-bottom: 16px; }
          .stats { display: grid; grid-template-columns: repeat(4, minmax(140px, 1fr)); gap: 10px; margin: 14px 0 20px; }
          .stat { border: 1px solid #d5dde8; border-radius: 10px; padding: 10px; }
          .label { font-size: 11px; color: #5b667a; text-transform: uppercase; letter-spacing: .02em; }
          .value { font-size: 16px; font-weight: 700; color: #0a2625; margin-top: 4px; }
          table { width: 100%; border-collapse: collapse; }
          th, td { border: 1px solid #e4e8f0; padding: 8px; font-size: 12px; text-align: left; }
          th { background: #f3f6fb; }
          tbody tr:nth-child(even) { background: #fafcff; }
          .footer { margin-top: 14px; font-size: 11px; color: #6a7488; }
          @media print { .no-print { display: none; } }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class="meta">Generated on ${format(new Date(), "dd MMM yyyy, h:mm a")}</div>
        <div class="stats">${statHtml}</div>
        <table>
          <thead><tr>${head}</tr></thead>
          <tbody>${body}</tbody>
        </table>
        <div class="footer">Generated by QuickPOS Platform</div>
        <script>
          window.onload = function () { window.print(); };
        </script>
      </body>
    </html>
  `);
  reportWindow.document.close();
}

export function parseCSV(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const text = String(e.target?.result || "");
      const lines = text.split(/\r?\n/).filter((line) => line.trim());
      if (!lines.length) {
        resolve({ headers: [], data: [], totalRows: 0 });
        return;
      }
      const headers = lines[0]
        .split(",")
        .map((header) => header.trim().toLowerCase().replace(/\s+/g, "_"));
      const data = lines.slice(1).map((line) => {
        const values = line.split(",");
        const row = {};
        headers.forEach((header, i) => {
          row[header] = values[i]?.trim() || "";
        });
        return row;
      });
      resolve({ headers, data, totalRows: data.length });
    };
    reader.onerror = reject;
    reader.readAsText(file);
  });
}
